import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Table, TableStyle
from reportlab.pdfgen import canvas


def generate_receipt_pdf(gym_name: str, payment, member_name: str, plan_name: str) -> io.BytesIO:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    navy = colors.HexColor("#0b1f33")
    cyan = colors.HexColor("#0891b2")
    pale = colors.HexColor("#ecfeff")
    muted = colors.HexColor("#64748b")
    left = 54
    right = width - 54

    c.setFillColor(navy)
    c.roundRect(left, height - 152, right - left, 98, 14, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left + 24, height - 92, gym_name[:42])
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#bae6fd"))
    c.drawString(left + 24, height - 112, "MEMBERSHIP PAYMENT RECEIPT")
    c.setFillColor(cyan)
    c.roundRect(right - 128, height - 126, 100, 28, 8, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(right - 78, height - 116, "PAID")

    styles = getSampleStyleSheet()
    label = ParagraphStyle("label", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=8, textColor=muted, leading=10)
    value = ParagraphStyle("value", parent=styles["Normal"], fontName="Helvetica", fontSize=11, textColor=navy, leading=14)
    details = [
        [Paragraph("RECEIPT NUMBER", label), Paragraph("PAYMENT DATE", label)],
        [Paragraph(str(payment.id)[:8].upper(), value), Paragraph(payment.payment_date.isoformat(), value)],
        [Paragraph("MEMBER", label), Paragraph("PLAN", label)],
        [Paragraph(member_name, value), Paragraph(plan_name, value)],
        [Paragraph("PAYMENT METHOD", label), Paragraph("TRANSACTION ID", label)],
        [Paragraph(payment.payment_method.replace("_", " ").title(), value), Paragraph(payment.transaction_id or "Not provided", value)],
    ]
    table = Table(details, colWidths=[(right - left) / 2] * 2, rowHeights=[18, 28, 18, 28, 18, 28])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), pale),
        ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#bae6fd")),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bae6fd")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
    ]))
    table.wrapOn(c, right - left, 120)
    table.drawOn(c, left, height - 310)

    c.setFillColor(colors.HexColor("#f8fafc"))
    c.roundRect(left, height - 400, right - left, 66, 10, fill=1, stroke=0)
    c.setFillColor(muted)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left + 18, height - 360, "TOTAL AMOUNT PAID")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 24)
    c.drawRightString(right - 18, height - 368, f"Rs. {float(payment.amount):,.2f}")

    y = height - 438
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left, y, "MEMBERSHIP DETAILS")
    c.setStrokeColor(colors.HexColor("#cbd5e1"))
    c.line(left, y - 8, right, y - 8)
    c.setFillColor(muted)
    c.setFont("Helvetica", 10)
    c.drawString(left, y - 30, "Next renewal")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(right, y - 30, payment.next_due_date.isoformat() if payment.next_due_date else "Not scheduled")

    c.setFillColor(muted)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, 58, "Thank you for keeping your fitness journey moving.")
    c.setFillColor(cyan)
    c.setFont("Helvetica-Bold", 9)
    c.drawRightString(right, 58, "Generated by Gym Console")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer


def generate_payslip_pdf(gym_name: str, staff_email: str, payroll) -> io.BytesIO:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    left = 54
    right = width - 54
    navy = colors.HexColor("#0b1f33")
    cyan = colors.HexColor("#0891b2")
    muted = colors.HexColor("#64748b")

    c.setFillColor(navy)
    c.roundRect(left, height - 152, right - left, 98, 14, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left + 24, height - 92, gym_name[:42])
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#bae6fd"))
    c.drawString(left + 24, height - 112, "STAFF PAYSLIP")
    c.setFillColor(cyan)
    c.roundRect(right - 128, height - 126, 100, 28, 8, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(right - 78, height - 116, payroll.status.value.upper())

    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, height - 198, f"Staff: {staff_email}")
    c.setFont("Helvetica", 10)
    c.setFillColor(muted)
    c.drawString(left, height - 218, f"Pay period: {payroll.pay_period_start} to {payroll.pay_period_end}")

    details = [
        ["Gross salary", f"Rs. {float(payroll.gross_amount):,.2f}"],
        ["Unpaid leave", f"{payroll.leave_days_unpaid} days"],
        ["Leave deduction", f"Rs. {float(payroll.leave_deduction_amount):,.2f}"],
        ["Leave deduction note", payroll.leave_deduction_override_note or "Automatic calculation"],
        ["Other deductions", f"Rs. {float(payroll.other_deductions):,.2f}"],
        ["Deduction note", payroll.other_deductions_note or "None"],
    ]
    table = Table(details, colWidths=[180, right - left - 180], rowHeights=[30] * len(details))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecfeff")),
        ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#bae6fd")),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bae6fd")),
        ("TEXTCOLOR", (0, 0), (0, -1), muted),
        ("TEXTCOLOR", (1, 0), (1, -1), navy),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
    ]))
    table.wrapOn(c, right - left, 180)
    table.drawOn(c, left, height - 410)

    c.setFillColor(colors.HexColor("#f8fafc"))
    c.roundRect(left, height - 500, right - left, 66, 10, fill=1, stroke=0)
    c.setFillColor(muted)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left + 18, height - 460, "NET AMOUNT RELEASED")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 24)
    c.drawRightString(right - 18, height - 468, f"Rs. {float(payroll.net_amount):,.2f}")

    c.setFillColor(muted)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, 58, "Generated by Gym Console")
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer


def generate_expense_summary_pdf(gym_name: str, start_date, end_date, total_payroll, total_other_expenses, total_income, by_month) -> io.BytesIO:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    left, right = 54, width - 54
    navy = colors.HexColor("#0b1f33")
    c.setFillColor(navy)
    c.roundRect(left, height - 152, right - left, 98, 14, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left + 24, height - 92, gym_name[:42])
    c.setFont("Helvetica", 10)
    c.drawString(left + 24, height - 112, "PAYROLL & EXPENSE SUMMARY")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, height - 198, f"Period: {start_date} to {end_date}")
    rows = [["Income", total_income], ["Payroll released", total_payroll], ["Other expenses", total_other_expenses], ["Total expenses", total_payroll + total_other_expenses], ["Net profit", total_income - total_payroll - total_other_expenses]]
    rows = [[label, f"Rs. {float(value):,.2f}"] for label, value in rows]
    table = Table(rows, colWidths=[180, right - left - 180], rowHeights=[30] * len(rows))
    table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ecfeff")), ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#bae6fd")), ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bae6fd")), ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 10), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("LEFTPADDING", (0, 0), (-1, -1), 14)]))
    table.wrapOn(c, right - left, 180)
    table.drawOn(c, left, height - 390)
    c.setFillColor(colors.HexColor("#64748b"))
    c.setFont("Helvetica", 10)
    y = height - 430
    for row in by_month:
        c.drawString(left, y, f"{row.month}: payroll Rs. {float(row.payroll):,.2f}, other Rs. {float(row.other_expenses):,.2f}")
        y -= 18
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, 58, "Generated by Gym Console")
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer
