import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Table, TableStyle
from reportlab.pdfgen import canvas


def generate_receipt_pdf(gym_name: str, payment, member_name: str, plan_name: str) -> io.BytesIO:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    navy = colors.HexColor("#0b1f33")
    cyan = colors.HexColor("#0891b2")
    pale = colors.HexColor("#ecfeff")
    muted = colors.HexColor("#64748b")
    left = 54
    right = width - 54

    c.setFillColor(navy)
    c.roundRect(left, height - 152, right - left, 98, 14, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(left + 24, height - 92, gym_name[:42])
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#bae6fd"))
    c.drawString(left + 24, height - 112, "MEMBERSHIP PAYMENT RECEIPT")
    c.setFillColor(cyan)
    c.roundRect(right - 128, height - 126, 100, 28, 8, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(right - 78, height - 116, "PAID")

    styles = getSampleStyleSheet()
    label = ParagraphStyle("label", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=8, textColor=muted, leading=10)
    value = ParagraphStyle("value", parent=styles["Normal"], fontName="Helvetica", fontSize=11, textColor=navy, leading=14)
    details = [
        [Paragraph("RECEIPT NUMBER", label), Paragraph("PAYMENT DATE", label)],
        [Paragraph(str(payment.id)[:8].upper(), value), Paragraph(payment.payment_date.isoformat(), value)],
        [Paragraph("MEMBER", label), Paragraph("PLAN", label)],
        [Paragraph(member_name, value), Paragraph(plan_name, value)],
        [Paragraph("PAYMENT METHOD", label), Paragraph("TRANSACTION ID", label)],
        [Paragraph(payment.payment_method.replace("_", " ").title(), value), Paragraph(payment.transaction_id or "Not provided", value)],
    ]
    table = Table(details, colWidths=[(right - left) / 2] * 2, rowHeights=[18, 28, 18, 28, 18, 28])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), pale),
        ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#bae6fd")),
        ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#bae6fd")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
    ]))
    table.wrapOn(c, right - left, 120)
    table.drawOn(c, left, height - 310)

    c.setFillColor(colors.HexColor("#f8fafc"))
    c.roundRect(left, height - 400, right - left, 66, 10, fill=1, stroke=0)
    c.setFillColor(muted)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(left + 18, height - 360, "TOTAL AMOUNT PAID")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 24)
    c.drawRightString(right - 18, height - 368, f"Rs. {float(payment.amount):,.2f}")

    y = height - 438
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(left, y, "MEMBERSHIP DETAILS")
    c.setStrokeColor(colors.HexColor("#cbd5e1"))
    c.line(left, y - 8, right, y - 8)
    c.setFillColor(muted)
    c.setFont("Helvetica", 10)
    c.drawString(left, y - 30, "Next renewal")
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(right, y - 30, payment.next_due_date.isoformat() if payment.next_due_date else "Not scheduled")

    c.setFillColor(muted)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, 58, "Thank you for keeping your fitness journey moving.")
    c.setFillColor(cyan)
    c.setFont("Helvetica-Bold", 9)
    c.drawRightString(right, 58, "Generated by Gym Console")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer
